dataSource.jdbcUrl = "jdbc:sqlite:/waltid-wallet-api/data/wallet.db"
dataSource.driverClassName = "org.sqlite.JDBC"
dataSource.username = ""
dataSource.password = ""
dataSource.maximumPoolSize = 5
dataSource.transactionIsolation = "TRANSACTION_SERIALIZABLE"
